name: HUD
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --dev
      - name: Lint script
        run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --dev
      - name: Build script
        run: npm run build
  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install --dev
      - name: Test script
        run: npm run test
